### ISSUE TITLE
[BUG] unable to cancel skyway pending tx

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2762]
When trying to cancel skyway tx [from the CW contract](https://github.com/VolumeFi/token-purchaser-cw/blob/main/contracts/collector/src/contract.rs#L164-L175) , the following error was received: 

```
paloma_sdk.exceptions.LCDResponseError: Status 500 - failed to execute message; message index: 0: dispatch: submessages: failed to dispatch message: unknown transaction with id 86 from sender paloma1xsamrrt562nt0czwl24ppcgqrnn04qm6sv5sh4zyjj3u9yfd0t7sut30ud: pool transaction: unknown [/home/runner/work/paloma/paloma/x/skyway/keeper/pool.go:237] with gas used: '95869'
```

However the tx exists 
```
    {
      "id": "86",
      "sender": "paloma1xsamrrt562nt0czwl24ppcgqrnn04qm6sv5sh4zyjj3u9yfd0t7sut30ud",
      "dest_address": "0x2FF7E2780D3C2ceb446394B4c4e5F4fd598f0064",
      "erc20_token": {
        "contract": "0x874De72D7A26865f3Ee448278e5Ba3896a2eB512",
        "amount": "47331584822696",
        "chain_reference_id": "arbitrum-main"
      },
      "bridge_tax_amount": "0"
```

**Comment by byte-bandit** [comment]
How exactly are you cancelling the transaction? Are you using the CLI or something else? Can you post the command?

**Comment by byte-bandit** [comment]
Transactions can only be cancelled when they're not in a batch. While they are part of an outgoing batch, they're locked. The batches are created every 50 blocks or so. You'll need to wait for a window where there is no current outgoing batch to cancel the TX.

**Comment by taariq** [comment]
> How exactly are you cancelling the transaction? Are you using the CLI or something else? Can you post the command?

We are using a Python script created here:
https://github.com/VolumeFi/talent-script/pull/225/commits/5f334dd704a5af71f05fc333258e041ee281e2fc

**Comment by taariq** [comment]
> Transactions can only be cancelled when they're not in a batch. While they are part of an outgoing batch, they're locked. The batches are created every 50 blocks or so. You'll need to wait for a window where there is no current outgoing batch to cancel the TX.

@byte-bandit will you clarify how we `wait for a window where there is no current outgoing batch to cancel the TX`. it's not clear from the instructions how we check for this window.

**Comment by taariq** [comment]
@verabehr are you able to add the list of transactions here so we have a list to make attempts to cancel?

**Comment by taariq** [comment]
https://arbiscan.io/address/0x3c1864a873879139c1bd87c7d95c4e475a91d19c#events  shows that the nonces are still increasing, but we need to cancel the transactions that are not in the batch.

**Comment by taariq** [comment]
From @byte-bandit: @fullstack412 @verabehr lets use this output to identify which transactions we can cancel

> The output of ‘Palomad q skyway outgoing-tx-batches arbitrum-main “”’ will not include a batch containing that transaction.

**Comment by verabehr** [comment]
> From [@byte-bandit](https://github.com/byte-bandit): [@fullstack412](https://github.com/fullstack412) [@verabehr](https://github.com/verabehr) lets use this output to identify which transactions we can cancel
> 
> > The output of ‘Palomad q skyway outgoing-tx-batches arbitrum-main “”’ will not include a batch containing that transaction.

I don't think I understand this sentence fully, but the quote signs are messed up. Here is the corrected version. However this returns just all transactions that we looked at before
```
palomad q skyway outgoing-tx-batches arbitrum-main ""
```


Here is a command to retrieve all transaction ids and the corresponding sender 
```
palomad q skyway outgoing-tx-batches arbitrum-main "" -oj | jq '.batches[]' | jq '.transactions[]' | jq -r '.id + "\t" + .sender'
```

Currently, we have these: 
```
133	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
111	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
126	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
96	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
119	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
103	paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
86	paloma1xsamrrt562nt0czwl24ppcgqrnn04qm6sv5sh4zyjj3u9yfd0t7sut30ud
85	paloma1g9s0agwwk9zgtpr2sjn32ghcrqes55ngchnx7e0d29fehzvguecqyt2dsw
```

**Comment by taariq** [comment]
@byte-bandit so @fullstack412 attempted to cancel each one of the above transactions one by own to see if any were NOT included in a batch and all his attempts failed. He is canceling each tx manually.

We see batches submitted every 30 seconds here: https://arbiscan.io/address/0x3c1864a873879139c1bd87c7d95c4e475a91d19c#events

In this moment, we do not have any documentation in Notion on how to determine your note:
> Transactions can only be cancelled when they're not in a batch. While they are part of an outgoing batch, they're locked. The batches are created every 50 blocks or so. You'll need to wait for a window where there is no current outgoing batch to cancel the TX.

**Comment by byte-bandit** [comment]
When you setup a Skyway transaction, Paloma will give it an `id`, not a hash, it's an increasing integer, e.g. `86`. Paloma sends out transactions in batches, and creates new batches every `n` blocks. If a batch cannot be confirmed (which is what is happening at the moment), the batch is being deleted and all txs it contained are moved back to the unbatched pool. Soon afterwards, a new batch will be created with any transactions currently in the pool.

In order to cancel an outgoing transaction and prevent it from being retried, you need to wait for this transaction to be in the pool of unbatched transactions. The skyway module is self documenting in its CLI methods, but you can find out in a couple of different ways. Let's suppose we want to cancel the tx with ID `88`:

- `palomad q skyway outgoing-tx-batches arbitrum-main "" -oj | jq | grep '"id": "88"'`: if you get an output, you know the transaction is currently in a batch. Wait until you do not see this ID pop up in the output, then you know it's currently not in a batch. That's when you want to send the cancel command. You will need to be fairly quick though, so best to prepare it beforehand.
- You can also use `palomad q skyway pending-txs SENDER-ADDRESS`. That will give you two fields: `transfers_in_batches: []` (ignore this) and `unbatched_transfers: []` Every transaction you can see in `unbatched_transfers` is currently available to be cancelled.

**Comment by taariq** [comment]
palomad q skyway pending-txs paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx --node https://rpc.palomachain.com:443

```
transfers_in_batches:
- bridge_tax_amount: "0"
  dest_address: 0x015D407e8967634A4E8Ac0CB2a4AF3CbCeae7337
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "134"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "112"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0xA3b473B9B14a1BF3fA9Fb26A9b9e749196d0f34E
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "97"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0xeDDc780478866f2A8A77D236b2dbd6c4eEC9c758
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "127"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x2eBAc388CE5d2500365f92b73C673Ff01253485c
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "120"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x2175e091176F43eD55313e4Bc31FE4E94051A6fE
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "104"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x015D407e8967634A4E8Ac0CB2a4AF3CbCeae7337
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "133"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "111"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0xeDDc780478866f2A8A77D236b2dbd6c4eEC9c758
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "126"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0xA3b473B9B14a1BF3fA9Fb26A9b9e749196d0f34E
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "96"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x2eBAc388CE5d2500365f92b73C673Ff01253485c
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "119"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x2175e091176F43eD55313e4Bc31FE4E94051A6fE
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "103"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
unbatched_transfers: []
```

**Comment by taariq** [comment]
Here's a list of unbatch transfers

```
unbatched_transfers:
- bridge_tax_amount: "0"
  dest_address: 0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "112"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0xA3b473B9B14a1BF3fA9Fb26A9b9e749196d0f34E
  erc20_token:
    amount: "100000000"
    chain_reference_id: matic-main
    contract: 0xE685B6989f98a748d0aeE4FF1Ed0bC7dCf7beBE7
  id: "97"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x015D407e8967634A4E8Ac0CB2a4AF3CbCeae7337
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "133"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
- bridge_tax_amount: "0"
  dest_address: 0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
  erc20_token:
    amount: "100000000"
    chain_reference_id: arbitrum-main
    contract: 0x97c86883E983a1C61eA894Cf6FDF2FA53fD4d225
  id: "111"
  sender: paloma18xrvj2ffxygkmtqwf3tr6fjqk3w0dgg7m6ucwx
```
