### ISSUE TITLE
[BUG] ARB-MAIN: Submit batch for GRAIN doesn't stop running. GRAINS are send ~every 10 minutes on ARB main

### ISSUE THREAD

**Issue by fullstack412** [VolumeFi/paloma#2869]
I sent 100 grain from paloma to arbitrum by using the paloma cli (for testing add_liqudity)
but i received 400 grains (100 grains * 4 times) on arbitrum chain for now and protocol is keep sending 100 grain tokens every 10 mins.

https://paloma.explorers.guru/transaction/2931F14968686C8B730C1886CF0680A801C82AC9C37708022319720F447397E3
https://arbiscan.io/token/0x93c654dee345fc27d34cef2cb0366510278842e5?a=0x2175e091176F43eD55313e4Bc31FE4E94051A6fE

Compass: https://arbiscan.io/address/0x3c1864a873879139C1BD87c7D95c4e475A91d19C

Last observed nonce on arbitrum (`palomad q skyway last-observed-nonce arbitrum-main`) is increasing and matches the last observed nonce on compass

**Comment by fullstack412** [comment]
I found a new bug while testing add_liquidity

I execute the add_liquidity function on vyper contract (sent  Grains, JKBD tokens), but on paloma side, I received JKBD token and Bobby token

It's the tx of add_liqudity execution
https://arbiscan.io/tx/0x19e79226e5999233ca1ded891b532047254283ccd7c60c76eb775a70519a2e70

and it's the balance of paloma side.
```
palomad q bank spendable-balances paloma1h7tk4naa9nnhp7nvtamfddvmdjn9k93dxv27t2g5wrn2lwtwk7dquu4e3j

balances:

- amount: "100000000"

  denom: factory/paloma1aqnpdw6g4nc6apzpww29suwcyhgqtgdef6z520g8wywgkx0579ushvs053/ubobby

- amount: "12011519563238"

  denom: factory/paloma1kpqenkph603uggcgdztq76ec35guzkn08v8qvq0ytk36sepynuysnmky9f/JKBD.41

pagination:

  total: "2"
```

I'm not sure whose bug is this. but looks like protocol.

As you can see, when I sent Grain from Paloma to EVM, the Grain token was bridged in Arbitrum. However, when I sent Grain token back from EVM to Paloma, Bobby token was bridged, not Grain token.

cc: @taariq @verabehr @wc117
