### ISSUE TITLE
Updates to register claim for curve

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#96]
# Background
https://etherscan.io/tx/0x668b2d77eaec1ff8a8ccbf9e7b2b9196b6eaed83f2ee5fd00663f26c18b5f308

Let's confirm that `register claim` api worked correctly for this TX

# Done when

- [ ] a list of items, when checked, this ticket should be considered to be finished

**Comment by verabehr** [comment]
looks like this worked as expected

**Comment by verabehr** [comment]
paloma tx hash is: 489B492FDDE71AB46F1C412C7527BC0975AD51B6D6D7D102AF99C762FE0FFC72 

details from tx: 
```
raw_log: '[{"events":[{"type":"execute","attributes":[{"key":"_contract_address","value":"paloma1sr06m8yqg0wzqqyqvzvp5t07dj4nevx9u8qc7j4qa72qu8e3ct8qsh6585"}]},{"type":"message","attributes":[{"key":"action","value":"/cosmwasm.wasm.v1.MsgExecuteContract"},{"key":"module","value":"wasm"},{"key":"sender","value":"paloma1ss8dxwjxhrt3nnxll377kujsn09sm3r087xfz8"}]},{"type":"wasm-register","attributes":[{"key":"_contract_address","value":"paloma1sr06m8yqg0wzqqyqvzvp5t07dj4nevx9u8qc7j4qa72qu8e3ct8qsh6585"},{"key":"address","value":"paloma1em7d6xl5ld3emyyynmyffsjpagak3250qw8tqv"},{"key":"claimable","value":"133888396"}]}]}]'
timestamp: "2023-03-29T14:15:09Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "3361"
        denom: ugrain
      gas_limit: "224036"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: A0Qf+BRxZAyXqQc0ozSsyEQq5Ng7jo5tNL2y5M1Bnoaj
      sequence: "440"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmwasm.wasm.v1.MsgExecuteContract
      contract: paloma1sr06m8yqg0wzqqyqvzvp5t07dj4nevx9u8qc7j4qa72qu8e3ct8qsh6585
      funds: []
      msg:
        register:
          tx_meta:
            address: paloma1em7d6xl5ld3emyyynmyffsjpagak3250qw8tqv
            amount: "7982345"
            tx_hash: 0x668b2d77eaec1ff8a8ccbf9e7b2b9196b6eaed83f2ee5fd00663f26c18b5f308
      sender: paloma1ss8dxwjxhrt3nnxll377kujsn09sm3r087xfz8
```
